# Generated by Django 5.0.4 on 2024-04-09 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type_of_event', models.CharField(choices=[('applied', 'applied'), ('interview', 'interview'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='applied', max_length=200)),
                ('time_spent', models.IntegerField()),
                ('comment', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.job')),
            ],
        ),
    ]
